name: Test Docker Build & Push

on:
  push:
    tags: ['v*']

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push to GHCR
        uses: ./
        with:
          image_name: ${{ github.repository_owner }}/test-docker-publish-ghcr
          tag: ''
          latest_tag: 'true'
          push: 'true'
